Stockcounter
ChestShop-authors/ChestShop-3 pull request #368
Opened 2020-10-13 19:36 UTC by bricefrisco

### OVERVIEW
This pull request is an implementation of an enhancement request https://github.com/ChestShop-authors/ChestShop-3/issues/365
This change will add a configuration property, that when enabled, will append a stock counter to the quantity line.

Here's an example:
```
Kozz
Q 10 : C 450
B 30 : S 20
Diamond
```

The stock counter will be added, removed, or updated when one of these three events occur:
 - ChestShop is created (PreShopCreation)
 - ChestShop is used (PostTransaction)
 - ChestShop inventory is closed (InventoryClose)
 
The method to obtain the stock count is relatively straight-forward.
 1. Use existing utility methods to parse the ITEM_LINE to determine the material the chest shop contains
 2. Use existing utility methods to determine how much of the specified item is in the chest shop
 3. Update the sign(s) on the chest shop with that information (Some new utility functions created to retrieve all of the sign(s) on a shop)
 
When the configuration setting is enabled, chest shops will automatically be updated when one of the three events above occur.
When the configuration setting is disabled, chest shops will automatically have the stock counter removed (if there is one) when one of the three events above occur.

This means all that needs to be done is to edit the configuration. Shops do not need to be manually modified or recreated.
 
A couple of slight modifications to existing code had to be made, although it did not require modifying nearly as much code as I had anticipated.

### CHANGES
 - Configurable property `USE_STOCK_COUNTER` created and defaulted to false.
 - Modified quantity line regular expression in `ChestShop.Signs.ChestShopSign` so trade shops with or without a stock counter pass validations.
 - Created new class `Breeze.Utils.QuantityUtil` responsible for determining if a trade shop has a stock counter, and parsing the quantity.
 - Slight (one-line) modifications to three classes to use the utility function mentioned above in place of `Integer.parseInt`
 - Created utility methods in `ChestShop.Utils.uBlock` to find all shop signs connected to a chest shop
 - Created new class `ChestShop.Signs.StockCounter` responsible for adding and removing the stock count to a specified sign.
 - Created new class `ChestShop.Listeners.PreShopCreation.StockCounterModifier` responsible for adding, removing, or modifying the stock count to the quantity line when a new shop is created
 - Created new class `ChestShop.Listeners.PostTransaction.StockCounterManager` responsible for adding, removing, or modifying the stock count to the quantity line after a transaction has been made
 - Created new package and class `ChestShop.Listeners.Inventory.InventoryClose` responsible for adding, removing, or modifying the stock count to the quantity line after a chest shop inventory has been closed
 - Modified `ChestShop.ChestShop` to configure new event listeners

### TEST CASES
**SHOP CREATION (USE_STOCK_COUNTER enabled)** `Listeners -> PreShopCreation -> StockCounterModifier`: 
- When a new shop is created, the count is automatically appended to the quantity line
- If a count is included when creating the sign, the count is updated to the correct amount
- If the shop is an admin shop, no count is added
- If the shop is an admin shop and the count is included when creating the sign, the count is removed
	
**SHOP CREATION (USE_STOCK_COUNTER disabled)** `Listeners -> PreShopCreation -> StockCounterModifier`:
- If a count is included when creating the sign, the count is removed
	
**TRANSACTION MADE (USE_STOCK_COUNTER enabled)** `Listeners -> PostTransaction -> StockCounterManager`:
- If the shop is an admin shop, no update occurs (no count on admin shops)
- The sign(s) on the chest shop are updated to reflect the current count(s) of respective items in the chest
		- If the sign does not already have a count, one is added automatically

**TRANSACTION MADE (USE_STOCK_COUNTER disabled)** `Listeners -> PostTransaction -> StockCounterManager`:
- If the sign has a counter, the counter is removed.
	
**INVENTORY CLOSED (USE_STOCK_COUNTER enabled)** `Listeners -> Inventory -> InventoryClose`:
- If the inventory is not a chest shop, nothing happens.
- All signs on the chest shop are updated to reflect the current count
	
**INVENTORY CLOSED (USE_STOCK_COUNTER disabled)** `Listeners -> Inventory -> InventoryClose`:
- If the inventory is not a chest shop, nothing happens.
- If any signs on the chest shop have a counter, they are removed

**If USE_STOCK_COUNTER enabled when MAX_SHOP_AMOUNT > 5 characters:**
- Plugin will act as if USE_STOCK_COUNTER is not enabled, while issuing a warning log to the console when the events are triggered.
	
**OTHER TESTS:**
- If a chest shop contains multiple signs, they're correctly identified (neighbor signs and chests are not affected)
- Transitions between turning the plugin on and off are seamless and automated
	

### POTENTIAL IMPROVEMENTS:
- StockCounter is not compatible with a configuration that also has MAX_SHOP_AMOUNT >= 6 digits, due to sign length limitations. There are some enhancements that can be made to potentially remove this limitation (removal of whitespace, calculation of QUANTITY_LINE length to add a stock counter wherever possible, instead of just disabling it altogether)
- Other than the quantity line on the sign, I do not modify any events. However, if there are any other plugins that utilize the quantity line in other code packages, this configuration setting could cause side effects to those other plugins.
- Signs will *always* be updated when one of the three metioned events occur. Enhancements can be made to optimize this to only update signs when it is actually necessary (for instance, on InventoryClose, the sign does not need to be updated if no items were placed or removed from the chest)
- I tried my best to follow the existing coding patterns throughout the repo and make the code as easy to read and follow as possible. If there are class names or method names that are ambiguous let me know
- Placement of class `QuantityUtil` inside of package `Breeze.Utils` is questionable
- Placement of class `StockCounter` inside of package `ChestShop.Signs` is questionable

Please let me know what you think. :)
Thanks!

2020-10-13 21:15 UTC, andrewkm commented
Yes please!
This would be great!

2020-10-14 17:07 UTC, Phoenix616 requested changes
Looks good regarding the approach but additional to the specific comments I would like to see a change regarding the overall structure: Seeing as other, optional functionalities are contained completely to their own module classes I would prefer it if this too was one module which contained all the required listeners (which are currently in `InventoryClose`, `StockCountermanager` and `StockCounterModifier`) and stock-specific util methods (the `StockCounter` ones). This would be better all in one class in the `Listeners.Modules` package and registered via the `registerModules` method.

2020-10-14 17:07 UTC, Phoenix616 commented on src/main/java/com/Acrobot/ChestShop/Listeners/Inventory/InventoryClose.java
> +        if (!ChestShopSign.isShopBlock(event.getInventory().getHolder())) {
I'm personally not really a fan of checking this on every inventory close. `Invenotry#getHolder` will cause the server to create a new BlockState copy if the inventory's holder is a block state which isn't really performant.

It would be better if we could find a way to check if its a shop without having to get the block state in such a way (e.g. via checking if the inventory type is valid before and then caching the holder to not create it again later or, more ideal, directly getting the block using `Inventory#getLocation`).

2020-10-14 17:07 UTC, Phoenix616 commented on src/main/java/com/Acrobot/ChestShop/Listeners/PostTransaction/TransactionLogger.java
> +import java.util.Arrays;
This seems to be an accident?

2020-10-14 17:07 UTC, Phoenix616 commented on src/main/java/com/Acrobot/ChestShop/Utils/uBlock.java
> +import org.bukkit.block.*;
Please don't use wildcard imports.

2020-10-14 18:35 UTC, bricefrisco commented
> Looks good regarding the approach but additional to the specific comments I would like to see a change regarding the overall structure: Seeing as other, optional functionalities are contained completely to their own module classes I would prefer it if this too was one module which contained all the required listeners (which are currently in `InventoryClose`, `StockCountermanager` and `StockCounterModifier`) and stock-specific util methods (the `StockCounter` ones). This would be better all in one class in the `Listeners.Modules` package and registered via the `registerModules` method.

Thanks for the feedback! Very helpful.

I did feel extremely awkward with the placement of these classes. Updating this would be difficult for any other developer unless they knew exactly where to look.

I'll take a look at the InventoryClose event and see what I can do, and condense these into a single class.

2020-10-15 01:03 UTC, bricefrisco commented on src/main/java/com/Acrobot/ChestShop/Listeners/Modules/StockCounterModule.java
> +        if (event.getInventory().getLocation() == null || !ChestShopSign.isShopBlock(event.getInventory().getLocation().getBlock())) {
@Phoenix616 is `!ChestShopSign.isShopBlock(event.getInventory().getLocation().getBlock()` reliable?

If `event.getInventory()` is from an Entity, and that Entity somehow glitches / exploits "into" a chest shop, is this potential for a bug as `event.getInventory().getLocation().getBlock()` does not seem to guarantee that the block is linked to that inventory.

I have added a check to `event.getInventory().getType().isCreatable()` which, (my presumption) should limit this to inventories of actual blocks, thus removing this potential.

Please let me know what you think.

2020-10-19 22:37 UTC, Phoenix616 commented on src/main/java/com/Acrobot/ChestShop/Listeners/Modules/StockCounterModule.java
> +        if (event.getInventory().getLocation() == null || !ChestShopSign.isShopBlock(event.getInventory().getLocation().getBlock())) {
While that might happen it doesn't really matter for this case as all it would do was update the sign.

I really don't think that we should use `isCreatable` there as that only states if an inventory type can be created with `Bukkit#createInventory` not if inventory type is of a block.

2020-10-23 19:17 UTC, bricefrisco commented on src/main/java/com/Acrobot/ChestShop/Listeners/Modules/StockCounterModule.java
> +        if (event.getInventory().getLocation() == null || !ChestShopSign.isShopBlock(event.getInventory().getLocation().getBlock())) {
Okay that makes sense, I've removed the check.

2020-10-23 19:19 UTC, bricefrisco commented
@Phoenix616 Removed the redundant/ineffective check in [above commit](https://github.com/ChestShop-authors/ChestShop-3/pull/368/commits/5e044523594a4dced290a220b687f849003bdd2c).

2020-10-23 22:02 UTC, Phoenix616 commented
Awesome, I hopefully find some time testing this in the next couple days!

2020-10-30 21:45 UTC, merged